---

vscode_repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
vscode_apt_key: "https://packages.microsoft.com/keys/microsoft.asc"

vscode_extensions:
  - aaron-bond.better-comments
  - formulahendry.code-runner
  - donjayamanne.githistory
  - eamodio.gitlens
  - golang.Go
  - vincaslt.highlight-matching-tag
  - oderwat.indent-rainbow
  - yzhang.markdown-all-in-one
  - PKief.material-icon-theme
  - ms-python.python
  - humao.rest-client
  - Gruntfuggly.todo-tree
  - shardulm94.trailing-spaces
  - Equinusocio.vsc-material-theme
  - vscodevim.vim
  - vscoss.vscode-ansible
  - wayou.vscode-todo-highlight
  - visualstudioexptteam.vscodeintellicode

...
